/**
 * Auto-generated by scripts/build-skill-digests.mjs.
 *
 * SHA-256 digests of the SKILL.md assets advertised by
 * /.well-known/agent-skills/index.json. Regenerate by running
 * `npm run build` (or `node scripts/build-skill-digests.mjs`)
 * after editing any SKILL.md.
 */

// Source: public/.well-known/agent-skills/marketplace-search/SKILL.md (2078 bytes)
export const MARKETPLACE_SEARCH_SHA256 = "9668e6083191cbe188d02ecba72fc405809025473970eede7d6bf2d2690f0045";
