/**
 * Auto-generated by scripts/build-skill-digests.mjs.
 *
 * SHA-256 digests of the SKILL.md assets advertised by
 * /.well-known/agent-skills/index.json. Regenerate by running
 * `npm run build` (or `node scripts/build-skill-digests.mjs`)
 * after editing any SKILL.md.
 */

// Source: public/.well-known/agent-skills/marketplace-search/SKILL.md (3987 bytes)
export const MARKETPLACE_SEARCH_SHA256 = "2fc5cbc3ccc55707c14dba5c128c4737d2c9ddbea0a950e288dcb2ebea5d8e75";
